### ISSUE TITLE
Version not found - 1.9.6 and higher + SPI import package problem

### ISSUE THREAD

**Issue by krystian-panek-vmltech** [wcm-io/io.wcm.caconfig.extensions#3]
https://wcm.io/caconfig/extensions/

![image](https://github.com/wcm-io/io.wcm.caconfig.extensions/assets/81212505/96a8359f-c4e4-405f-95b7-51e601775c91)

https://mvnrepository.com/artifact/io.wcm/io.wcm.caconfig.extensions

![image](https://github.com/wcm-io/io.wcm.caconfig.extensions/assets/81212505/dd64e42a-2d6c-47ce-a3eb-86564d3f3236)

I have AEM 6.5.20 and cannot run the bundle properly:

![image](https://github.com/wcm-io/io.wcm.caconfig.extensions/assets/81212505/4dc2d072-ce15-4e3e-b993-6c3d6725f81a)

Also I cannot find SPI 2.2+ required as dependency...

Is it even runnable on recent AEM?

Problem occurs since 1.9.0 ( https://github.com/wcm-io/io.wcm.caconfig.extensions/compare/1.8.8...1.9.0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R75 ) ; I just confirmed. The 1.8.8 version is the last one working on SP 20.

**Comment by stefanseifert** [comment]
the information was contained in the changelog https://wcm.io/caconfig/extensions/changes-report.html but was probably a bit too hidden - i've update the main page as well: https://wcm.io/caconfig/extensions/

in order to run the extensions bundle 1.9.0 or higher you need to deploy recent versions of `org.apache.sling.caconfig.api`, `org.apache.sling.caconfig.spi`, `org.apache.sling.caconfig.impl` - those included in AEM 6.5 (even with latest SP) are quite outdated.
