### ISSUE TITLE
Missing Context-Aware Configuration After Deploy 

### ISSUE THREAD

**Issue by NmurtasDev** [wcm-io/io.wcm.caconfig.extensions#6]
We installed the context-aware configuration on an AEM cloud service instance. 
But after deployment, we missed the configuration.
According to the guide, we have already enabled the persistence strategy: AEM page, but this solution doesn't work.

**Comment by stefanseifert** [comment]
hmm, that's difficult to tell the root cause from that description.

if i understand correctly, existing context-aware configurations that you stored before deploying `io.wcm.caconfig.extensions` are not longer found = could no longer be resolved after deploying it? `io.wcm.caconfig.extensions` adds additional persistence strategies without disabling the default ones, so normally this should not happen and existing configurations should be resolvable as well.

to see whats going on internally, you can enabled `DEBUG` or even `TRACE` logging in AEM for these two log categories:
* `org.apache.sling.caconfig`
* `io.wcm.caconfig`
